/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IInstanceInfo extends Serializable {

    /**
     * Setter for <code>comp_net_fusion.instance_info.instanceID</code>. 实例编号
     */
    public void setInstanceid(String value);

    /**
     * Getter for <code>comp_net_fusion.instance_info.instanceID</code>. 实例编号
     */
    public String getInstanceid();

    /**
     * Setter for <code>comp_net_fusion.instance_info.vmImageID</code>. 所在虚拟机镜像id
     */
    public void setVmimageid(String value);

    /**
     * Getter for <code>comp_net_fusion.instance_info.vmImageID</code>. 所在虚拟机镜像id
     */
    public String getVmimageid();

    /**
     * Setter for <code>comp_net_fusion.instance_info.totalCpu</code>. cpu分配量
     */
    public void setTotalcpu(Long value);

    /**
     * Getter for <code>comp_net_fusion.instance_info.totalCpu</code>. cpu分配量
     */
    public Long getTotalcpu();

    /**
     * Setter for <code>comp_net_fusion.instance_info.totalMem</code>. 内存分配量
     */
    public void setTotalmem(Long value);

    /**
     * Getter for <code>comp_net_fusion.instance_info.totalMem</code>. 内存分配量
     */
    public Long getTotalmem();

    /**
     * Setter for <code>comp_net_fusion.instance_info.totalDisk</code>. 存储空间分配量
     */
    public void setTotaldisk(Long value);

    /**
     * Getter for <code>comp_net_fusion.instance_info.totalDisk</code>. 存储空间分配量
     */
    public Long getTotaldisk();

    /**
     * Setter for <code>comp_net_fusion.instance_info.usedCpu</code>. cpu使用量
     */
    public void setUsedcpu(Long value);

    /**
     * Getter for <code>comp_net_fusion.instance_info.usedCpu</code>. cpu使用量
     */
    public Long getUsedcpu();

    /**
     * Setter for <code>comp_net_fusion.instance_info.usedMem</code>. 内存使用量
     */
    public void setUsedmem(Long value);

    /**
     * Getter for <code>comp_net_fusion.instance_info.usedMem</code>. 内存使用量
     */
    public Long getUsedmem();

    /**
     * Setter for <code>comp_net_fusion.instance_info.usedDisk</code>. 磁盘使用量
     */
    public void setUseddisk(Long value);

    /**
     * Getter for <code>comp_net_fusion.instance_info.usedDisk</code>. 磁盘使用量
     */
    public Long getUseddisk();

    /**
     * Setter for <code>comp_net_fusion.instance_info.rRequestNum</code>. 读取请求数量
     */
    public void setRrequestnum(Integer value);

    /**
     * Getter for <code>comp_net_fusion.instance_info.rRequestNum</code>. 读取请求数量
     */
    public Integer getRrequestnum();

    /**
     * Setter for <code>comp_net_fusion.instance_info.wRequestNum</code>. 写入请求数量
     */
    public void setWrequestnum(Integer value);

    /**
     * Getter for <code>comp_net_fusion.instance_info.wRequestNum</code>. 写入请求数量
     */
    public Integer getWrequestnum();

    /**
     * Setter for <code>comp_net_fusion.instance_info.readBytes</code>. 读取字节数
     */
    public void setReadbytes(Long value);

    /**
     * Getter for <code>comp_net_fusion.instance_info.readBytes</code>. 读取字节数
     */
    public Long getReadbytes();

    /**
     * Setter for <code>comp_net_fusion.instance_info.writeBytes</code>. 写入字节数
     */
    public void setWritebytes(Long value);

    /**
     * Getter for <code>comp_net_fusion.instance_info.writeBytes</code>. 写入字节数
     */
    public Long getWritebytes();

    /**
     * Setter for <code>comp_net_fusion.instance_info.timeStamp</code>. 时间戳
     */
    public void setTimestamp(Long value);

    /**
     * Getter for <code>comp_net_fusion.instance_info.timeStamp</code>. 时间戳
     */
    public Long getTimestamp();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IInstanceInfo
     */
    public void from(com.pandalu.workloadservice.db.tables.interfaces.IInstanceInfo from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IInstanceInfo
     */
    public <E extends com.pandalu.workloadservice.db.tables.interfaces.IInstanceInfo> E into(E into);
}
