/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IK8sPodInfo extends Serializable {

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.uid</code>. 唯一标识符
     */
    public void setUid(String value);

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.uid</code>. 唯一标识符
     */
    public String getUid();

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.name</code>. pod名称
     */
    public void setName(String value);

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.name</code>. pod名称
     */
    public String getName();

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.ip</code>. pod ip
     */
    public void setIp(String value);

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.ip</code>. pod ip
     */
    public String getIp();

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.ownerNode</code>. 所在node
     */
    public void setOwnernode(String value);

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.ownerNode</code>. 所在node
     */
    public String getOwnernode();

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.usedCpu</code>. 已使用cpu
     */
    public void setUsedcpu(String value);

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.usedCpu</code>. 已使用cpu
     */
    public String getUsedcpu();

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.usedMemory</code>. 已使用内存
     */
    public void setUsedmemory(String value);

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.usedMemory</code>. 已使用内存
     */
    public String getUsedmemory();

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.timestamp</code>. 时间戳
     */
    public void setTimestamp(ULong value);

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.timestamp</code>. 时间戳
     */
    public ULong getTimestamp();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IK8sPodInfo
     */
    public void from(com.pandalu.workloadservice.db.tables.interfaces.IK8sPodInfo from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IK8sPodInfo
     */
    public <E extends com.pandalu.workloadservice.db.tables.interfaces.IK8sPodInfo> E into(E into);
}
