/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IK8sContainerInfo extends Serializable {

    /**
     * Setter for <code>comp_net_fusion.k8s_container_info.name</code>. pod名称
     */
    public void setName(String value);

    /**
     * Getter for <code>comp_net_fusion.k8s_container_info.name</code>. pod名称
     */
    public String getName();

    /**
     * Setter for <code>comp_net_fusion.k8s_container_info.ownerPod</code>. 所属pod
     */
    public void setOwnerpod(String value);

    /**
     * Getter for <code>comp_net_fusion.k8s_container_info.ownerPod</code>. 所属pod
     */
    public String getOwnerpod();

    /**
     * Setter for <code>comp_net_fusion.k8s_container_info.minCpu</code>. 最少Cpu需求量
     */
    public void setMincpu(String value);

    /**
     * Getter for <code>comp_net_fusion.k8s_container_info.minCpu</code>. 最少Cpu需求量
     */
    public String getMincpu();

    /**
     * Setter for <code>comp_net_fusion.k8s_container_info.minMemory</code>. 最小内存需求量
     */
    public void setMinmemory(String value);

    /**
     * Getter for <code>comp_net_fusion.k8s_container_info.minMemory</code>. 最小内存需求量
     */
    public String getMinmemory();

    /**
     * Setter for <code>comp_net_fusion.k8s_container_info.maxCpu</code>. 最大cpu需求量
     */
    public void setMaxcpu(String value);

    /**
     * Getter for <code>comp_net_fusion.k8s_container_info.maxCpu</code>. 最大cpu需求量
     */
    public String getMaxcpu();

    /**
     * Setter for <code>comp_net_fusion.k8s_container_info.maxMemory</code>. 最大内存需求量
     */
    public void setMaxmemory(String value);

    /**
     * Getter for <code>comp_net_fusion.k8s_container_info.maxMemory</code>. 最大内存需求量
     */
    public String getMaxmemory();

    /**
     * Setter for <code>comp_net_fusion.k8s_container_info.timestamp</code>. 时间戳
     */
    public void setTimestamp(ULong value);

    /**
     * Getter for <code>comp_net_fusion.k8s_container_info.timestamp</code>. 时间戳
     */
    public ULong getTimestamp();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IK8sContainerInfo
     */
    public void from(com.pandalu.workloadservice.db.tables.interfaces.IK8sContainerInfo from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IK8sContainerInfo
     */
    public <E extends com.pandalu.workloadservice.db.tables.interfaces.IK8sContainerInfo> E into(E into);
}
