/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IMap extends Serializable {

    /**
     * Setter for <code>comp_net_fusion.map.ID</code>. 物理机所在城市城市代码
     */
    public void setId(Integer value);

    /**
     * Getter for <code>comp_net_fusion.map.ID</code>. 物理机所在城市城市代码
     */
    public Integer getId();

    /**
     * Setter for <code>comp_net_fusion.map.name</code>. 物理机所在城市名
     */
    public void setName(String value);

    /**
     * Getter for <code>comp_net_fusion.map.name</code>. 物理机所在城市名
     */
    public String getName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IMap
     */
    public void from(com.pandalu.workloadservice.db.tables.interfaces.IMap from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IMap
     */
    public <E extends com.pandalu.workloadservice.db.tables.interfaces.IMap> E into(E into);
}
