/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IPmInfo extends Serializable {

    /**
     * Setter for <code>comp_net_fusion.pm_info.uuid</code>. 物理机id
     */
    public void setUuid(String value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.uuid</code>. 物理机id
     */
    public String getUuid();

    /**
     * Setter for <code>comp_net_fusion.pm_info.pmID</code>. 物理机编号
     */
    public void setPmid(String value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.pmID</code>. 物理机编号
     */
    public String getPmid();

    /**
     * Setter for <code>comp_net_fusion.pm_info.pmName</code>. 物理机名称
     */
    public void setPmname(String value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.pmName</code>. 物理机名称
     */
    public String getPmname();

    /**
     * Setter for <code>comp_net_fusion.pm_info.state</code>. 物理主机运行状态
     */
    public void setState(Integer value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.state</code>. 物理主机运行状态
     */
    public Integer getState();

    /**
     * Setter for <code>comp_net_fusion.pm_info.city</code>. 物理机所在城市城市代码
     */
    public void setCity(Integer value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.city</code>. 物理机所在城市城市代码
     */
    public Integer getCity();

    /**
     * Setter for <code>comp_net_fusion.pm_info.pmIP</code>.
     */
    public void setPmip(String value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.pmIP</code>.
     */
    public String getPmip();

    /**
     * Setter for <code>comp_net_fusion.pm_info.totalCpu</code>. 物理主机总 CPU
     */
    public void setTotalcpu(Long value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.totalCpu</code>. 物理主机总 CPU
     */
    public Long getTotalcpu();

    /**
     * Setter for <code>comp_net_fusion.pm_info.totalMem</code>. 物理主机总内存
     */
    public void setTotalmem(Long value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.totalMem</code>. 物理主机总内存
     */
    public Long getTotalmem();

    /**
     * Setter for <code>comp_net_fusion.pm_info.totalBand</code>. 物理主机总带宽
     */
    public void setTotalband(Long value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.totalBand</code>. 物理主机总带宽
     */
    public Long getTotalband();

    /**
     * Setter for <code>comp_net_fusion.pm_info.totalDisk</code>. 物理主机总硬盘
     */
    public void setTotaldisk(Long value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.totalDisk</code>. 物理主机总硬盘
     */
    public Long getTotaldisk();

    /**
     * Setter for <code>comp_net_fusion.pm_info.usedCpu</code>. 物理主机已消耗的 CPU
     */
    public void setUsedcpu(Long value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.usedCpu</code>. 物理主机已消耗的 CPU
     */
    public Long getUsedcpu();

    /**
     * Setter for <code>comp_net_fusion.pm_info.usedMem</code>. 物理主机已消耗的内存
     */
    public void setUsedmem(Long value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.usedMem</code>. 物理主机已消耗的内存
     */
    public Long getUsedmem();

    /**
     * Setter for <code>comp_net_fusion.pm_info.usedBand</code>. 物理主机已消耗的带宽
     */
    public void setUsedband(Long value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.usedBand</code>. 物理主机已消耗的带宽
     */
    public Long getUsedband();

    /**
     * Setter for <code>comp_net_fusion.pm_info.usedDisk</code>. 物理主机已消耗的硬盘
     */
    public void setUseddisk(Long value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.usedDisk</code>. 物理主机已消耗的硬盘
     */
    public Long getUseddisk();

    /**
     * Setter for <code>comp_net_fusion.pm_info.nVms</code>. 运行的虚拟机数
     */
    public void setNvms(Integer value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.nVms</code>. 运行的虚拟机数
     */
    public Integer getNvms();

    /**
     * Setter for <code>comp_net_fusion.pm_info.timeStamp</code>. 时间戳
     */
    public void setTimestamp(Long value);

    /**
     * Getter for <code>comp_net_fusion.pm_info.timeStamp</code>. 时间戳
     */
    public Long getTimestamp();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IPmInfo
     */
    public void from(com.pandalu.workloadservice.db.tables.interfaces.IPmInfo from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IPmInfo
     */
    public <E extends com.pandalu.workloadservice.db.tables.interfaces.IPmInfo> E into(E into);
}
