/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IVmimages extends Serializable {

    /**
     * Setter for <code>comp_net_fusion.vmimages.vmImageID</code>. 虚拟机镜像编号
     */
    public void setVmimageid(String value);

    /**
     * Getter for <code>comp_net_fusion.vmimages.vmImageID</code>. 虚拟机镜像编号
     */
    public String getVmimageid();

    /**
     * Setter for <code>comp_net_fusion.vmimages.imgSize</code>. 虚拟机镜像文件大小
     */
    public void setImgsize(Double value);

    /**
     * Getter for <code>comp_net_fusion.vmimages.imgSize</code>. 虚拟机镜像文件大小
     */
    public Double getImgsize();

    /**
     * Setter for <code>comp_net_fusion.vmimages.imgCPU</code>. 镜像CPU信息
     */
    public void setImgcpu(String value);

    /**
     * Getter for <code>comp_net_fusion.vmimages.imgCPU</code>. 镜像CPU信息
     */
    public String getImgcpu();

    /**
     * Setter for <code>comp_net_fusion.vmimages.imgMem</code>. 镜像内存信息
     */
    public void setImgmem(String value);

    /**
     * Getter for <code>comp_net_fusion.vmimages.imgMem</code>. 镜像内存信息
     */
    public String getImgmem();

    /**
     * Setter for <code>comp_net_fusion.vmimages.imgDisk</code>. 镜像存储信息
     */
    public void setImgdisk(String value);

    /**
     * Getter for <code>comp_net_fusion.vmimages.imgDisk</code>. 镜像存储信息
     */
    public String getImgdisk();

    /**
     * Setter for <code>comp_net_fusion.vmimages.imgOS</code>. 镜像操作系统
     */
    public void setImgos(String value);

    /**
     * Getter for <code>comp_net_fusion.vmimages.imgOS</code>. 镜像操作系统
     */
    public String getImgos();

    /**
     * Setter for <code>comp_net_fusion.vmimages.NetworkAdapter</code>. 联网方式
     */
    public void setNetworkadapter(String value);

    /**
     * Getter for <code>comp_net_fusion.vmimages.NetworkAdapter</code>. 联网方式
     */
    public String getNetworkadapter();

    /**
     * Setter for <code>comp_net_fusion.vmimages.timeStamp</code>. 时间戳
     */
    public void setTimestamp(Long value);

    /**
     * Getter for <code>comp_net_fusion.vmimages.timeStamp</code>. 时间戳
     */
    public Long getTimestamp();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IVmimages
     */
    public void from(com.pandalu.workloadservice.db.tables.interfaces.IVmimages from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IVmimages
     */
    public <E extends com.pandalu.workloadservice.db.tables.interfaces.IVmimages> E into(E into);
}
