/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IVmInfo extends Serializable {

    /**
     * Setter for <code>comp_net_fusion.vm_info.uuid</code>. 唯一标识符
     */
    public void setUuid(String value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.uuid</code>. 唯一标识符
     */
    public String getUuid();

    /**
     * Setter for <code>comp_net_fusion.vm_info.vmID</code>. 虚拟机编号
     */
    public void setVmid(String value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.vmID</code>. 虚拟机编号
     */
    public String getVmid();

    /**
     * Setter for <code>comp_net_fusion.vm_info.pmID</code>. 所在物理机编号
     */
    public void setPmid(String value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.pmID</code>. 所在物理机编号
     */
    public String getPmid();

    /**
     * Setter for <code>comp_net_fusion.vm_info.vmImageID</code>. 虚拟机所属镜像ID
     */
    public void setVmimageid(String value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.vmImageID</code>. 虚拟机所属镜像ID
     */
    public String getVmimageid();

    /**
     * Setter for <code>comp_net_fusion.vm_info.vmName</code>. 虚拟机名称
     */
    public void setVmname(String value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.vmName</code>. 虚拟机名称
     */
    public String getVmname();

    /**
     * Setter for <code>comp_net_fusion.vm_info.status</code>. 虚拟机状态
     */
    public void setStatus(Integer value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.status</code>. 虚拟机状态
     */
    public Integer getStatus();

    /**
     * Setter for <code>comp_net_fusion.vm_info.totalCpu</code>. 虚拟机cpu分配量
     */
    public void setTotalcpu(Long value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.totalCpu</code>. 虚拟机cpu分配量
     */
    public Long getTotalcpu();

    /**
     * Setter for <code>comp_net_fusion.vm_info.totalMem</code>. 虚拟机内存分配量
     */
    public void setTotalmem(Long value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.totalMem</code>. 虚拟机内存分配量
     */
    public Long getTotalmem();

    /**
     * Setter for <code>comp_net_fusion.vm_info.totalDisk</code>. 虚拟机存储空间分配量
     */
    public void setTotaldisk(Long value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.totalDisk</code>. 虚拟机存储空间分配量
     */
    public Long getTotaldisk();

    /**
     * Setter for <code>comp_net_fusion.vm_info.totalBand</code>. 虚拟机带宽分配量
     */
    public void setTotalband(Long value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.totalBand</code>. 虚拟机带宽分配量
     */
    public Long getTotalband();

    /**
     * Setter for <code>comp_net_fusion.vm_info.usedCpu</code>. 虚拟机cpu使用量
     */
    public void setUsedcpu(Long value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.usedCpu</code>. 虚拟机cpu使用量
     */
    public Long getUsedcpu();

    /**
     * Setter for <code>comp_net_fusion.vm_info.usedMem</code>. 虚拟机内存使用量
     */
    public void setUsedmem(Long value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.usedMem</code>. 虚拟机内存使用量
     */
    public Long getUsedmem();

    /**
     * Setter for <code>comp_net_fusion.vm_info.usedDisk</code>. 虚拟机存储空间使用量
     */
    public void setUseddisk(Long value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.usedDisk</code>. 虚拟机存储空间使用量
     */
    public Long getUseddisk();

    /**
     * Setter for <code>comp_net_fusion.vm_info.usedBand</code>. 虚拟机带宽使用量
     */
    public void setUsedband(Long value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.usedBand</code>. 虚拟机带宽使用量
     */
    public Long getUsedband();

    /**
     * Setter for <code>comp_net_fusion.vm_info.timeStamp</code>. 时间戳
     */
    public void setTimestamp(ULong value);

    /**
     * Getter for <code>comp_net_fusion.vm_info.timeStamp</code>. 时间戳
     */
    public ULong getTimestamp();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IVmInfo
     */
    public void from(com.pandalu.workloadservice.db.tables.interfaces.IVmInfo from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IVmInfo
     */
    public <E extends com.pandalu.workloadservice.db.tables.interfaces.IVmInfo> E into(E into);
}
