/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.records;


import com.pandalu.workloadservice.db.tables.InstanceInfo;
import com.pandalu.workloadservice.db.tables.interfaces.IInstanceInfo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstanceInfoRecord extends UpdatableRecordImpl<InstanceInfoRecord> implements Record13<String, String, Long, Long, Long, Long, Long, Long, Integer, Integer, Long, Long, Long>, IInstanceInfo {

    private static final long serialVersionUID = 187277450;

    /**
     * Setter for <code>comp_net_fusion.instance_info.instanceID</code>. 实例编号
     */
    @Override
    public void setInstanceid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>comp_net_fusion.instance_info.instanceID</code>. 实例编号
     */
    @Override
    public String getInstanceid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>comp_net_fusion.instance_info.vmImageID</code>. 所在虚拟机镜像id
     */
    @Override
    public void setVmimageid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>comp_net_fusion.instance_info.vmImageID</code>. 所在虚拟机镜像id
     */
    @Override
    public String getVmimageid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>comp_net_fusion.instance_info.totalCpu</code>. cpu分配量
     */
    @Override
    public void setTotalcpu(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>comp_net_fusion.instance_info.totalCpu</code>. cpu分配量
     */
    @Override
    public Long getTotalcpu() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>comp_net_fusion.instance_info.totalMem</code>. 内存分配量
     */
    @Override
    public void setTotalmem(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>comp_net_fusion.instance_info.totalMem</code>. 内存分配量
     */
    @Override
    public Long getTotalmem() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>comp_net_fusion.instance_info.totalDisk</code>. 存储空间分配量
     */
    @Override
    public void setTotaldisk(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>comp_net_fusion.instance_info.totalDisk</code>. 存储空间分配量
     */
    @Override
    public Long getTotaldisk() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>comp_net_fusion.instance_info.usedCpu</code>. cpu使用量
     */
    @Override
    public void setUsedcpu(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>comp_net_fusion.instance_info.usedCpu</code>. cpu使用量
     */
    @Override
    public Long getUsedcpu() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>comp_net_fusion.instance_info.usedMem</code>. 内存使用量
     */
    @Override
    public void setUsedmem(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>comp_net_fusion.instance_info.usedMem</code>. 内存使用量
     */
    @Override
    public Long getUsedmem() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>comp_net_fusion.instance_info.usedDisk</code>. 磁盘使用量
     */
    @Override
    public void setUseddisk(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>comp_net_fusion.instance_info.usedDisk</code>. 磁盘使用量
     */
    @Override
    public Long getUseddisk() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>comp_net_fusion.instance_info.rRequestNum</code>. 读取请求数量
     */
    @Override
    public void setRrequestnum(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>comp_net_fusion.instance_info.rRequestNum</code>. 读取请求数量
     */
    @Override
    public Integer getRrequestnum() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>comp_net_fusion.instance_info.wRequestNum</code>. 写入请求数量
     */
    @Override
    public void setWrequestnum(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>comp_net_fusion.instance_info.wRequestNum</code>. 写入请求数量
     */
    @Override
    public Integer getWrequestnum() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>comp_net_fusion.instance_info.readBytes</code>. 读取字节数
     */
    @Override
    public void setReadbytes(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>comp_net_fusion.instance_info.readBytes</code>. 读取字节数
     */
    @Override
    public Long getReadbytes() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>comp_net_fusion.instance_info.writeBytes</code>. 写入字节数
     */
    @Override
    public void setWritebytes(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>comp_net_fusion.instance_info.writeBytes</code>. 写入字节数
     */
    @Override
    public Long getWritebytes() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>comp_net_fusion.instance_info.timeStamp</code>. 时间戳
     */
    @Override
    public void setTimestamp(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>comp_net_fusion.instance_info.timeStamp</code>. 时间戳
     */
    @Override
    public Long getTimestamp() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<String, String, Long, Long, Long, Long, Long, Long, Integer, Integer, Long, Long, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<String, String, Long, Long, Long, Long, Long, Long, Integer, Integer, Long, Long, Long> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return InstanceInfo.INSTANCE_INFO.INSTANCEID;
    }

    @Override
    public Field<String> field2() {
        return InstanceInfo.INSTANCE_INFO.VMIMAGEID;
    }

    @Override
    public Field<Long> field3() {
        return InstanceInfo.INSTANCE_INFO.TOTALCPU;
    }

    @Override
    public Field<Long> field4() {
        return InstanceInfo.INSTANCE_INFO.TOTALMEM;
    }

    @Override
    public Field<Long> field5() {
        return InstanceInfo.INSTANCE_INFO.TOTALDISK;
    }

    @Override
    public Field<Long> field6() {
        return InstanceInfo.INSTANCE_INFO.USEDCPU;
    }

    @Override
    public Field<Long> field7() {
        return InstanceInfo.INSTANCE_INFO.USEDMEM;
    }

    @Override
    public Field<Long> field8() {
        return InstanceInfo.INSTANCE_INFO.USEDDISK;
    }

    @Override
    public Field<Integer> field9() {
        return InstanceInfo.INSTANCE_INFO.RREQUESTNUM;
    }

    @Override
    public Field<Integer> field10() {
        return InstanceInfo.INSTANCE_INFO.WREQUESTNUM;
    }

    @Override
    public Field<Long> field11() {
        return InstanceInfo.INSTANCE_INFO.READBYTES;
    }

    @Override
    public Field<Long> field12() {
        return InstanceInfo.INSTANCE_INFO.WRITEBYTES;
    }

    @Override
    public Field<Long> field13() {
        return InstanceInfo.INSTANCE_INFO.TIMESTAMP;
    }

    @Override
    public String component1() {
        return getInstanceid();
    }

    @Override
    public String component2() {
        return getVmimageid();
    }

    @Override
    public Long component3() {
        return getTotalcpu();
    }

    @Override
    public Long component4() {
        return getTotalmem();
    }

    @Override
    public Long component5() {
        return getTotaldisk();
    }

    @Override
    public Long component6() {
        return getUsedcpu();
    }

    @Override
    public Long component7() {
        return getUsedmem();
    }

    @Override
    public Long component8() {
        return getUseddisk();
    }

    @Override
    public Integer component9() {
        return getRrequestnum();
    }

    @Override
    public Integer component10() {
        return getWrequestnum();
    }

    @Override
    public Long component11() {
        return getReadbytes();
    }

    @Override
    public Long component12() {
        return getWritebytes();
    }

    @Override
    public Long component13() {
        return getTimestamp();
    }

    @Override
    public String value1() {
        return getInstanceid();
    }

    @Override
    public String value2() {
        return getVmimageid();
    }

    @Override
    public Long value3() {
        return getTotalcpu();
    }

    @Override
    public Long value4() {
        return getTotalmem();
    }

    @Override
    public Long value5() {
        return getTotaldisk();
    }

    @Override
    public Long value6() {
        return getUsedcpu();
    }

    @Override
    public Long value7() {
        return getUsedmem();
    }

    @Override
    public Long value8() {
        return getUseddisk();
    }

    @Override
    public Integer value9() {
        return getRrequestnum();
    }

    @Override
    public Integer value10() {
        return getWrequestnum();
    }

    @Override
    public Long value11() {
        return getReadbytes();
    }

    @Override
    public Long value12() {
        return getWritebytes();
    }

    @Override
    public Long value13() {
        return getTimestamp();
    }

    @Override
    public InstanceInfoRecord value1(String value) {
        setInstanceid(value);
        return this;
    }

    @Override
    public InstanceInfoRecord value2(String value) {
        setVmimageid(value);
        return this;
    }

    @Override
    public InstanceInfoRecord value3(Long value) {
        setTotalcpu(value);
        return this;
    }

    @Override
    public InstanceInfoRecord value4(Long value) {
        setTotalmem(value);
        return this;
    }

    @Override
    public InstanceInfoRecord value5(Long value) {
        setTotaldisk(value);
        return this;
    }

    @Override
    public InstanceInfoRecord value6(Long value) {
        setUsedcpu(value);
        return this;
    }

    @Override
    public InstanceInfoRecord value7(Long value) {
        setUsedmem(value);
        return this;
    }

    @Override
    public InstanceInfoRecord value8(Long value) {
        setUseddisk(value);
        return this;
    }

    @Override
    public InstanceInfoRecord value9(Integer value) {
        setRrequestnum(value);
        return this;
    }

    @Override
    public InstanceInfoRecord value10(Integer value) {
        setWrequestnum(value);
        return this;
    }

    @Override
    public InstanceInfoRecord value11(Long value) {
        setReadbytes(value);
        return this;
    }

    @Override
    public InstanceInfoRecord value12(Long value) {
        setWritebytes(value);
        return this;
    }

    @Override
    public InstanceInfoRecord value13(Long value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public InstanceInfoRecord values(String value1, String value2, Long value3, Long value4, Long value5, Long value6, Long value7, Long value8, Integer value9, Integer value10, Long value11, Long value12, Long value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IInstanceInfo from) {
        setInstanceid(from.getInstanceid());
        setVmimageid(from.getVmimageid());
        setTotalcpu(from.getTotalcpu());
        setTotalmem(from.getTotalmem());
        setTotaldisk(from.getTotaldisk());
        setUsedcpu(from.getUsedcpu());
        setUsedmem(from.getUsedmem());
        setUseddisk(from.getUseddisk());
        setRrequestnum(from.getRrequestnum());
        setWrequestnum(from.getWrequestnum());
        setReadbytes(from.getReadbytes());
        setWritebytes(from.getWritebytes());
        setTimestamp(from.getTimestamp());
    }

    @Override
    public <E extends IInstanceInfo> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InstanceInfoRecord
     */
    public InstanceInfoRecord() {
        super(InstanceInfo.INSTANCE_INFO);
    }

    /**
     * Create a detached, initialised InstanceInfoRecord
     */
    public InstanceInfoRecord(String instanceid, String vmimageid, Long totalcpu, Long totalmem, Long totaldisk, Long usedcpu, Long usedmem, Long useddisk, Integer rrequestnum, Integer wrequestnum, Long readbytes, Long writebytes, Long timestamp) {
        super(InstanceInfo.INSTANCE_INFO);

        set(0, instanceid);
        set(1, vmimageid);
        set(2, totalcpu);
        set(3, totalmem);
        set(4, totaldisk);
        set(5, usedcpu);
        set(6, usedmem);
        set(7, useddisk);
        set(8, rrequestnum);
        set(9, wrequestnum);
        set(10, readbytes);
        set(11, writebytes);
        set(12, timestamp);
    }
}
