/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.records;


import com.pandalu.workloadservice.db.tables.K8sPodInfo;
import com.pandalu.workloadservice.db.tables.interfaces.IK8sPodInfo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class K8sPodInfoRecord extends UpdatableRecordImpl<K8sPodInfoRecord> implements Record7<String, String, String, String, String, String, ULong>, IK8sPodInfo {

    private static final long serialVersionUID = -1186862895;

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.uid</code>. 唯一标识符
     */
    @Override
    public void setUid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.uid</code>. 唯一标识符
     */
    @Override
    public String getUid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.name</code>. pod名称
     */
    @Override
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.name</code>. pod名称
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.ip</code>. pod ip
     */
    @Override
    public void setIp(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.ip</code>. pod ip
     */
    @Override
    public String getIp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.ownerNode</code>. 所在node
     */
    @Override
    public void setOwnernode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.ownerNode</code>. 所在node
     */
    @Override
    public String getOwnernode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.usedCpu</code>. 已使用cpu
     */
    @Override
    public void setUsedcpu(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.usedCpu</code>. 已使用cpu
     */
    @Override
    public String getUsedcpu() {
        return (String) get(4);
    }

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.usedMemory</code>. 已使用内存
     */
    @Override
    public void setUsedmemory(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.usedMemory</code>. 已使用内存
     */
    @Override
    public String getUsedmemory() {
        return (String) get(5);
    }

    /**
     * Setter for <code>comp_net_fusion.k8s_pod_info.timestamp</code>. 时间戳
     */
    @Override
    public void setTimestamp(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>comp_net_fusion.k8s_pod_info.timestamp</code>. 时间戳
     */
    @Override
    public ULong getTimestamp() {
        return (ULong) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, String, String, ULong> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, String, String, String, String, ULong> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return K8sPodInfo.K8S_POD_INFO.UID;
    }

    @Override
    public Field<String> field2() {
        return K8sPodInfo.K8S_POD_INFO.NAME;
    }

    @Override
    public Field<String> field3() {
        return K8sPodInfo.K8S_POD_INFO.IP;
    }

    @Override
    public Field<String> field4() {
        return K8sPodInfo.K8S_POD_INFO.OWNERNODE;
    }

    @Override
    public Field<String> field5() {
        return K8sPodInfo.K8S_POD_INFO.USEDCPU;
    }

    @Override
    public Field<String> field6() {
        return K8sPodInfo.K8S_POD_INFO.USEDMEMORY;
    }

    @Override
    public Field<ULong> field7() {
        return K8sPodInfo.K8S_POD_INFO.TIMESTAMP;
    }

    @Override
    public String component1() {
        return getUid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getIp();
    }

    @Override
    public String component4() {
        return getOwnernode();
    }

    @Override
    public String component5() {
        return getUsedcpu();
    }

    @Override
    public String component6() {
        return getUsedmemory();
    }

    @Override
    public ULong component7() {
        return getTimestamp();
    }

    @Override
    public String value1() {
        return getUid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getIp();
    }

    @Override
    public String value4() {
        return getOwnernode();
    }

    @Override
    public String value5() {
        return getUsedcpu();
    }

    @Override
    public String value6() {
        return getUsedmemory();
    }

    @Override
    public ULong value7() {
        return getTimestamp();
    }

    @Override
    public K8sPodInfoRecord value1(String value) {
        setUid(value);
        return this;
    }

    @Override
    public K8sPodInfoRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public K8sPodInfoRecord value3(String value) {
        setIp(value);
        return this;
    }

    @Override
    public K8sPodInfoRecord value4(String value) {
        setOwnernode(value);
        return this;
    }

    @Override
    public K8sPodInfoRecord value5(String value) {
        setUsedcpu(value);
        return this;
    }

    @Override
    public K8sPodInfoRecord value6(String value) {
        setUsedmemory(value);
        return this;
    }

    @Override
    public K8sPodInfoRecord value7(ULong value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public K8sPodInfoRecord values(String value1, String value2, String value3, String value4, String value5, String value6, ULong value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IK8sPodInfo from) {
        setUid(from.getUid());
        setName(from.getName());
        setIp(from.getIp());
        setOwnernode(from.getOwnernode());
        setUsedcpu(from.getUsedcpu());
        setUsedmemory(from.getUsedmemory());
        setTimestamp(from.getTimestamp());
    }

    @Override
    public <E extends IK8sPodInfo> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached K8sPodInfoRecord
     */
    public K8sPodInfoRecord() {
        super(K8sPodInfo.K8S_POD_INFO);
    }

    /**
     * Create a detached, initialised K8sPodInfoRecord
     */
    public K8sPodInfoRecord(String uid, String name, String ip, String ownernode, String usedcpu, String usedmemory, ULong timestamp) {
        super(K8sPodInfo.K8S_POD_INFO);

        set(0, uid);
        set(1, name);
        set(2, ip);
        set(3, ownernode);
        set(4, usedcpu);
        set(5, usedmemory);
        set(6, timestamp);
    }
}
