/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.records;


import com.pandalu.workloadservice.db.tables.PmInfo;
import com.pandalu.workloadservice.db.tables.interfaces.IPmInfo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Record2;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PmInfoRecord extends UpdatableRecordImpl<PmInfoRecord> implements Record16<String, String, String, Integer, Integer, String, Long, Long, Long, Long, Long, Long, Long, Long, Integer, Long>, IPmInfo {

    private static final long serialVersionUID = -509599578;

    /**
     * Setter for <code>comp_net_fusion.pm_info.uuid</code>. 物理机id
     */
    @Override
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.uuid</code>. 物理机id
     */
    @Override
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.pmID</code>. 物理机编号
     */
    @Override
    public void setPmid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.pmID</code>. 物理机编号
     */
    @Override
    public String getPmid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.pmName</code>. 物理机名称
     */
    @Override
    public void setPmname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.pmName</code>. 物理机名称
     */
    @Override
    public String getPmname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.state</code>. 物理主机运行状态
     */
    @Override
    public void setState(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.state</code>. 物理主机运行状态
     */
    @Override
    public Integer getState() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.city</code>. 物理机所在城市城市代码
     */
    @Override
    public void setCity(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.city</code>. 物理机所在城市城市代码
     */
    @Override
    public Integer getCity() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.pmIP</code>.
     */
    @Override
    public void setPmip(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.pmIP</code>.
     */
    @Override
    public String getPmip() {
        return (String) get(5);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.totalCpu</code>. 物理主机总 CPU
     */
    @Override
    public void setTotalcpu(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.totalCpu</code>. 物理主机总 CPU
     */
    @Override
    public Long getTotalcpu() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.totalMem</code>. 物理主机总内存
     */
    @Override
    public void setTotalmem(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.totalMem</code>. 物理主机总内存
     */
    @Override
    public Long getTotalmem() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.totalBand</code>. 物理主机总带宽
     */
    @Override
    public void setTotalband(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.totalBand</code>. 物理主机总带宽
     */
    @Override
    public Long getTotalband() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.totalDisk</code>. 物理主机总硬盘
     */
    @Override
    public void setTotaldisk(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.totalDisk</code>. 物理主机总硬盘
     */
    @Override
    public Long getTotaldisk() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.usedCpu</code>. 物理主机已消耗的 CPU
     */
    @Override
    public void setUsedcpu(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.usedCpu</code>. 物理主机已消耗的 CPU
     */
    @Override
    public Long getUsedcpu() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.usedMem</code>. 物理主机已消耗的内存
     */
    @Override
    public void setUsedmem(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.usedMem</code>. 物理主机已消耗的内存
     */
    @Override
    public Long getUsedmem() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.usedBand</code>. 物理主机已消耗的带宽
     */
    @Override
    public void setUsedband(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.usedBand</code>. 物理主机已消耗的带宽
     */
    @Override
    public Long getUsedband() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.usedDisk</code>. 物理主机已消耗的硬盘
     */
    @Override
    public void setUseddisk(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.usedDisk</code>. 物理主机已消耗的硬盘
     */
    @Override
    public Long getUseddisk() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.nVms</code>. 运行的虚拟机数
     */
    @Override
    public void setNvms(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.nVms</code>. 运行的虚拟机数
     */
    @Override
    public Integer getNvms() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>comp_net_fusion.pm_info.timeStamp</code>. 时间戳
     */
    @Override
    public void setTimestamp(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>comp_net_fusion.pm_info.timeStamp</code>. 时间戳
     */
    @Override
    public Long getTimestamp() {
        return (Long) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<String, String, String, Integer, Integer, String, Long, Long, Long, Long, Long, Long, Long, Long, Integer, Long> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<String, String, String, Integer, Integer, String, Long, Long, Long, Long, Long, Long, Long, Long, Integer, Long> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PmInfo.PM_INFO.UUID;
    }

    @Override
    public Field<String> field2() {
        return PmInfo.PM_INFO.PMID;
    }

    @Override
    public Field<String> field3() {
        return PmInfo.PM_INFO.PMNAME;
    }

    @Override
    public Field<Integer> field4() {
        return PmInfo.PM_INFO.STATE;
    }

    @Override
    public Field<Integer> field5() {
        return PmInfo.PM_INFO.CITY;
    }

    @Override
    public Field<String> field6() {
        return PmInfo.PM_INFO.PMIP;
    }

    @Override
    public Field<Long> field7() {
        return PmInfo.PM_INFO.TOTALCPU;
    }

    @Override
    public Field<Long> field8() {
        return PmInfo.PM_INFO.TOTALMEM;
    }

    @Override
    public Field<Long> field9() {
        return PmInfo.PM_INFO.TOTALBAND;
    }

    @Override
    public Field<Long> field10() {
        return PmInfo.PM_INFO.TOTALDISK;
    }

    @Override
    public Field<Long> field11() {
        return PmInfo.PM_INFO.USEDCPU;
    }

    @Override
    public Field<Long> field12() {
        return PmInfo.PM_INFO.USEDMEM;
    }

    @Override
    public Field<Long> field13() {
        return PmInfo.PM_INFO.USEDBAND;
    }

    @Override
    public Field<Long> field14() {
        return PmInfo.PM_INFO.USEDDISK;
    }

    @Override
    public Field<Integer> field15() {
        return PmInfo.PM_INFO.NVMS;
    }

    @Override
    public Field<Long> field16() {
        return PmInfo.PM_INFO.TIMESTAMP;
    }

    @Override
    public String component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getPmid();
    }

    @Override
    public String component3() {
        return getPmname();
    }

    @Override
    public Integer component4() {
        return getState();
    }

    @Override
    public Integer component5() {
        return getCity();
    }

    @Override
    public String component6() {
        return getPmip();
    }

    @Override
    public Long component7() {
        return getTotalcpu();
    }

    @Override
    public Long component8() {
        return getTotalmem();
    }

    @Override
    public Long component9() {
        return getTotalband();
    }

    @Override
    public Long component10() {
        return getTotaldisk();
    }

    @Override
    public Long component11() {
        return getUsedcpu();
    }

    @Override
    public Long component12() {
        return getUsedmem();
    }

    @Override
    public Long component13() {
        return getUsedband();
    }

    @Override
    public Long component14() {
        return getUseddisk();
    }

    @Override
    public Integer component15() {
        return getNvms();
    }

    @Override
    public Long component16() {
        return getTimestamp();
    }

    @Override
    public String value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getPmid();
    }

    @Override
    public String value3() {
        return getPmname();
    }

    @Override
    public Integer value4() {
        return getState();
    }

    @Override
    public Integer value5() {
        return getCity();
    }

    @Override
    public String value6() {
        return getPmip();
    }

    @Override
    public Long value7() {
        return getTotalcpu();
    }

    @Override
    public Long value8() {
        return getTotalmem();
    }

    @Override
    public Long value9() {
        return getTotalband();
    }

    @Override
    public Long value10() {
        return getTotaldisk();
    }

    @Override
    public Long value11() {
        return getUsedcpu();
    }

    @Override
    public Long value12() {
        return getUsedmem();
    }

    @Override
    public Long value13() {
        return getUsedband();
    }

    @Override
    public Long value14() {
        return getUseddisk();
    }

    @Override
    public Integer value15() {
        return getNvms();
    }

    @Override
    public Long value16() {
        return getTimestamp();
    }

    @Override
    public PmInfoRecord value1(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public PmInfoRecord value2(String value) {
        setPmid(value);
        return this;
    }

    @Override
    public PmInfoRecord value3(String value) {
        setPmname(value);
        return this;
    }

    @Override
    public PmInfoRecord value4(Integer value) {
        setState(value);
        return this;
    }

    @Override
    public PmInfoRecord value5(Integer value) {
        setCity(value);
        return this;
    }

    @Override
    public PmInfoRecord value6(String value) {
        setPmip(value);
        return this;
    }

    @Override
    public PmInfoRecord value7(Long value) {
        setTotalcpu(value);
        return this;
    }

    @Override
    public PmInfoRecord value8(Long value) {
        setTotalmem(value);
        return this;
    }

    @Override
    public PmInfoRecord value9(Long value) {
        setTotalband(value);
        return this;
    }

    @Override
    public PmInfoRecord value10(Long value) {
        setTotaldisk(value);
        return this;
    }

    @Override
    public PmInfoRecord value11(Long value) {
        setUsedcpu(value);
        return this;
    }

    @Override
    public PmInfoRecord value12(Long value) {
        setUsedmem(value);
        return this;
    }

    @Override
    public PmInfoRecord value13(Long value) {
        setUsedband(value);
        return this;
    }

    @Override
    public PmInfoRecord value14(Long value) {
        setUseddisk(value);
        return this;
    }

    @Override
    public PmInfoRecord value15(Integer value) {
        setNvms(value);
        return this;
    }

    @Override
    public PmInfoRecord value16(Long value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public PmInfoRecord values(String value1, String value2, String value3, Integer value4, Integer value5, String value6, Long value7, Long value8, Long value9, Long value10, Long value11, Long value12, Long value13, Long value14, Integer value15, Long value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IPmInfo from) {
        setUuid(from.getUuid());
        setPmid(from.getPmid());
        setPmname(from.getPmname());
        setState(from.getState());
        setCity(from.getCity());
        setPmip(from.getPmip());
        setTotalcpu(from.getTotalcpu());
        setTotalmem(from.getTotalmem());
        setTotalband(from.getTotalband());
        setTotaldisk(from.getTotaldisk());
        setUsedcpu(from.getUsedcpu());
        setUsedmem(from.getUsedmem());
        setUsedband(from.getUsedband());
        setUseddisk(from.getUseddisk());
        setNvms(from.getNvms());
        setTimestamp(from.getTimestamp());
    }

    @Override
    public <E extends IPmInfo> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PmInfoRecord
     */
    public PmInfoRecord() {
        super(PmInfo.PM_INFO);
    }

    /**
     * Create a detached, initialised PmInfoRecord
     */
    public PmInfoRecord(String uuid, String pmid, String pmname, Integer state, Integer city, String pmip, Long totalcpu, Long totalmem, Long totalband, Long totaldisk, Long usedcpu, Long usedmem, Long usedband, Long useddisk, Integer nvms, Long timestamp) {
        super(PmInfo.PM_INFO);

        set(0, uuid);
        set(1, pmid);
        set(2, pmname);
        set(3, state);
        set(4, city);
        set(5, pmip);
        set(6, totalcpu);
        set(7, totalmem);
        set(8, totalband);
        set(9, totaldisk);
        set(10, usedcpu);
        set(11, usedmem);
        set(12, usedband);
        set(13, useddisk);
        set(14, nvms);
        set(15, timestamp);
    }
}
