/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.records;


import com.pandalu.workloadservice.db.tables.VmInfo;
import com.pandalu.workloadservice.db.tables.interfaces.IVmInfo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Record4;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VmInfoRecord extends UpdatableRecordImpl<VmInfoRecord> implements Record15<String, String, String, String, String, Integer, Long, Long, Long, Long, Long, Long, Long, Long, ULong>, IVmInfo {

    private static final long serialVersionUID = 1385830711;

    /**
     * Setter for <code>comp_net_fusion.vm_info.uuid</code>. 唯一标识符
     */
    @Override
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.uuid</code>. 唯一标识符
     */
    @Override
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.vmID</code>. 虚拟机编号
     */
    @Override
    public void setVmid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.vmID</code>. 虚拟机编号
     */
    @Override
    public String getVmid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.pmID</code>. 所在物理机编号
     */
    @Override
    public void setPmid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.pmID</code>. 所在物理机编号
     */
    @Override
    public String getPmid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.vmImageID</code>. 虚拟机所属镜像ID
     */
    @Override
    public void setVmimageid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.vmImageID</code>. 虚拟机所属镜像ID
     */
    @Override
    public String getVmimageid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.vmName</code>. 虚拟机名称
     */
    @Override
    public void setVmname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.vmName</code>. 虚拟机名称
     */
    @Override
    public String getVmname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.status</code>. 虚拟机状态
     */
    @Override
    public void setStatus(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.status</code>. 虚拟机状态
     */
    @Override
    public Integer getStatus() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.totalCpu</code>. 虚拟机cpu分配量
     */
    @Override
    public void setTotalcpu(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.totalCpu</code>. 虚拟机cpu分配量
     */
    @Override
    public Long getTotalcpu() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.totalMem</code>. 虚拟机内存分配量
     */
    @Override
    public void setTotalmem(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.totalMem</code>. 虚拟机内存分配量
     */
    @Override
    public Long getTotalmem() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.totalDisk</code>. 虚拟机存储空间分配量
     */
    @Override
    public void setTotaldisk(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.totalDisk</code>. 虚拟机存储空间分配量
     */
    @Override
    public Long getTotaldisk() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.totalBand</code>. 虚拟机带宽分配量
     */
    @Override
    public void setTotalband(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.totalBand</code>. 虚拟机带宽分配量
     */
    @Override
    public Long getTotalband() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.usedCpu</code>. 虚拟机cpu使用量
     */
    @Override
    public void setUsedcpu(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.usedCpu</code>. 虚拟机cpu使用量
     */
    @Override
    public Long getUsedcpu() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.usedMem</code>. 虚拟机内存使用量
     */
    @Override
    public void setUsedmem(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.usedMem</code>. 虚拟机内存使用量
     */
    @Override
    public Long getUsedmem() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.usedDisk</code>. 虚拟机存储空间使用量
     */
    @Override
    public void setUseddisk(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.usedDisk</code>. 虚拟机存储空间使用量
     */
    @Override
    public Long getUseddisk() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.usedBand</code>. 虚拟机带宽使用量
     */
    @Override
    public void setUsedband(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.usedBand</code>. 虚拟机带宽使用量
     */
    @Override
    public Long getUsedband() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>comp_net_fusion.vm_info.timeStamp</code>. 时间戳
     */
    @Override
    public void setTimestamp(ULong value) {
        set(14, value);
    }

    /**
     * Getter for <code>comp_net_fusion.vm_info.timeStamp</code>. 时间戳
     */
    @Override
    public ULong getTimestamp() {
        return (ULong) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record4<String, String, String, String> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<String, String, String, String, String, Integer, Long, Long, Long, Long, Long, Long, Long, Long, ULong> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<String, String, String, String, String, Integer, Long, Long, Long, Long, Long, Long, Long, Long, ULong> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return VmInfo.VM_INFO.UUID;
    }

    @Override
    public Field<String> field2() {
        return VmInfo.VM_INFO.VMID;
    }

    @Override
    public Field<String> field3() {
        return VmInfo.VM_INFO.PMID;
    }

    @Override
    public Field<String> field4() {
        return VmInfo.VM_INFO.VMIMAGEID;
    }

    @Override
    public Field<String> field5() {
        return VmInfo.VM_INFO.VMNAME;
    }

    @Override
    public Field<Integer> field6() {
        return VmInfo.VM_INFO.STATUS;
    }

    @Override
    public Field<Long> field7() {
        return VmInfo.VM_INFO.TOTALCPU;
    }

    @Override
    public Field<Long> field8() {
        return VmInfo.VM_INFO.TOTALMEM;
    }

    @Override
    public Field<Long> field9() {
        return VmInfo.VM_INFO.TOTALDISK;
    }

    @Override
    public Field<Long> field10() {
        return VmInfo.VM_INFO.TOTALBAND;
    }

    @Override
    public Field<Long> field11() {
        return VmInfo.VM_INFO.USEDCPU;
    }

    @Override
    public Field<Long> field12() {
        return VmInfo.VM_INFO.USEDMEM;
    }

    @Override
    public Field<Long> field13() {
        return VmInfo.VM_INFO.USEDDISK;
    }

    @Override
    public Field<Long> field14() {
        return VmInfo.VM_INFO.USEDBAND;
    }

    @Override
    public Field<ULong> field15() {
        return VmInfo.VM_INFO.TIMESTAMP;
    }

    @Override
    public String component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getVmid();
    }

    @Override
    public String component3() {
        return getPmid();
    }

    @Override
    public String component4() {
        return getVmimageid();
    }

    @Override
    public String component5() {
        return getVmname();
    }

    @Override
    public Integer component6() {
        return getStatus();
    }

    @Override
    public Long component7() {
        return getTotalcpu();
    }

    @Override
    public Long component8() {
        return getTotalmem();
    }

    @Override
    public Long component9() {
        return getTotaldisk();
    }

    @Override
    public Long component10() {
        return getTotalband();
    }

    @Override
    public Long component11() {
        return getUsedcpu();
    }

    @Override
    public Long component12() {
        return getUsedmem();
    }

    @Override
    public Long component13() {
        return getUseddisk();
    }

    @Override
    public Long component14() {
        return getUsedband();
    }

    @Override
    public ULong component15() {
        return getTimestamp();
    }

    @Override
    public String value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getVmid();
    }

    @Override
    public String value3() {
        return getPmid();
    }

    @Override
    public String value4() {
        return getVmimageid();
    }

    @Override
    public String value5() {
        return getVmname();
    }

    @Override
    public Integer value6() {
        return getStatus();
    }

    @Override
    public Long value7() {
        return getTotalcpu();
    }

    @Override
    public Long value8() {
        return getTotalmem();
    }

    @Override
    public Long value9() {
        return getTotaldisk();
    }

    @Override
    public Long value10() {
        return getTotalband();
    }

    @Override
    public Long value11() {
        return getUsedcpu();
    }

    @Override
    public Long value12() {
        return getUsedmem();
    }

    @Override
    public Long value13() {
        return getUseddisk();
    }

    @Override
    public Long value14() {
        return getUsedband();
    }

    @Override
    public ULong value15() {
        return getTimestamp();
    }

    @Override
    public VmInfoRecord value1(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public VmInfoRecord value2(String value) {
        setVmid(value);
        return this;
    }

    @Override
    public VmInfoRecord value3(String value) {
        setPmid(value);
        return this;
    }

    @Override
    public VmInfoRecord value4(String value) {
        setVmimageid(value);
        return this;
    }

    @Override
    public VmInfoRecord value5(String value) {
        setVmname(value);
        return this;
    }

    @Override
    public VmInfoRecord value6(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public VmInfoRecord value7(Long value) {
        setTotalcpu(value);
        return this;
    }

    @Override
    public VmInfoRecord value8(Long value) {
        setTotalmem(value);
        return this;
    }

    @Override
    public VmInfoRecord value9(Long value) {
        setTotaldisk(value);
        return this;
    }

    @Override
    public VmInfoRecord value10(Long value) {
        setTotalband(value);
        return this;
    }

    @Override
    public VmInfoRecord value11(Long value) {
        setUsedcpu(value);
        return this;
    }

    @Override
    public VmInfoRecord value12(Long value) {
        setUsedmem(value);
        return this;
    }

    @Override
    public VmInfoRecord value13(Long value) {
        setUseddisk(value);
        return this;
    }

    @Override
    public VmInfoRecord value14(Long value) {
        setUsedband(value);
        return this;
    }

    @Override
    public VmInfoRecord value15(ULong value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public VmInfoRecord values(String value1, String value2, String value3, String value4, String value5, Integer value6, Long value7, Long value8, Long value9, Long value10, Long value11, Long value12, Long value13, Long value14, ULong value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IVmInfo from) {
        setUuid(from.getUuid());
        setVmid(from.getVmid());
        setPmid(from.getPmid());
        setVmimageid(from.getVmimageid());
        setVmname(from.getVmname());
        setStatus(from.getStatus());
        setTotalcpu(from.getTotalcpu());
        setTotalmem(from.getTotalmem());
        setTotaldisk(from.getTotaldisk());
        setTotalband(from.getTotalband());
        setUsedcpu(from.getUsedcpu());
        setUsedmem(from.getUsedmem());
        setUseddisk(from.getUseddisk());
        setUsedband(from.getUsedband());
        setTimestamp(from.getTimestamp());
    }

    @Override
    public <E extends IVmInfo> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VmInfoRecord
     */
    public VmInfoRecord() {
        super(VmInfo.VM_INFO);
    }

    /**
     * Create a detached, initialised VmInfoRecord
     */
    public VmInfoRecord(String uuid, String vmid, String pmid, String vmimageid, String vmname, Integer status, Long totalcpu, Long totalmem, Long totaldisk, Long totalband, Long usedcpu, Long usedmem, Long useddisk, Long usedband, ULong timestamp) {
        super(VmInfo.VM_INFO);

        set(0, uuid);
        set(1, vmid);
        set(2, pmid);
        set(3, vmimageid);
        set(4, vmname);
        set(5, status);
        set(6, totalcpu);
        set(7, totalmem);
        set(8, totaldisk);
        set(9, totalband);
        set(10, usedcpu);
        set(11, usedmem);
        set(12, useddisk);
        set(13, usedband);
        set(14, timestamp);
    }
}
