/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.pojos;


import com.pandalu.workloadservice.db.tables.interfaces.IInstanceInfo;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InstanceInfo implements IInstanceInfo {

    private static final long serialVersionUID = 962461217;

    private String  instanceid;
    private String  vmimageid;
    private Long    totalcpu;
    private Long    totalmem;
    private Long    totaldisk;
    private Long    usedcpu;
    private Long    usedmem;
    private Long    useddisk;
    private Integer rrequestnum;
    private Integer wrequestnum;
    private Long    readbytes;
    private Long    writebytes;
    private Long    timestamp;

    public InstanceInfo() {}

    public InstanceInfo(IInstanceInfo value) {
        this.instanceid = value.getInstanceid();
        this.vmimageid = value.getVmimageid();
        this.totalcpu = value.getTotalcpu();
        this.totalmem = value.getTotalmem();
        this.totaldisk = value.getTotaldisk();
        this.usedcpu = value.getUsedcpu();
        this.usedmem = value.getUsedmem();
        this.useddisk = value.getUseddisk();
        this.rrequestnum = value.getRrequestnum();
        this.wrequestnum = value.getWrequestnum();
        this.readbytes = value.getReadbytes();
        this.writebytes = value.getWritebytes();
        this.timestamp = value.getTimestamp();
    }

    public InstanceInfo(
        String  instanceid,
        String  vmimageid,
        Long    totalcpu,
        Long    totalmem,
        Long    totaldisk,
        Long    usedcpu,
        Long    usedmem,
        Long    useddisk,
        Integer rrequestnum,
        Integer wrequestnum,
        Long    readbytes,
        Long    writebytes,
        Long    timestamp
    ) {
        this.instanceid = instanceid;
        this.vmimageid = vmimageid;
        this.totalcpu = totalcpu;
        this.totalmem = totalmem;
        this.totaldisk = totaldisk;
        this.usedcpu = usedcpu;
        this.usedmem = usedmem;
        this.useddisk = useddisk;
        this.rrequestnum = rrequestnum;
        this.wrequestnum = wrequestnum;
        this.readbytes = readbytes;
        this.writebytes = writebytes;
        this.timestamp = timestamp;
    }

    @Override
    public String getInstanceid() {
        return this.instanceid;
    }

    @Override
    public void setInstanceid(String instanceid) {
        this.instanceid = instanceid;
    }

    @Override
    public String getVmimageid() {
        return this.vmimageid;
    }

    @Override
    public void setVmimageid(String vmimageid) {
        this.vmimageid = vmimageid;
    }

    @Override
    public Long getTotalcpu() {
        return this.totalcpu;
    }

    @Override
    public void setTotalcpu(Long totalcpu) {
        this.totalcpu = totalcpu;
    }

    @Override
    public Long getTotalmem() {
        return this.totalmem;
    }

    @Override
    public void setTotalmem(Long totalmem) {
        this.totalmem = totalmem;
    }

    @Override
    public Long getTotaldisk() {
        return this.totaldisk;
    }

    @Override
    public void setTotaldisk(Long totaldisk) {
        this.totaldisk = totaldisk;
    }

    @Override
    public Long getUsedcpu() {
        return this.usedcpu;
    }

    @Override
    public void setUsedcpu(Long usedcpu) {
        this.usedcpu = usedcpu;
    }

    @Override
    public Long getUsedmem() {
        return this.usedmem;
    }

    @Override
    public void setUsedmem(Long usedmem) {
        this.usedmem = usedmem;
    }

    @Override
    public Long getUseddisk() {
        return this.useddisk;
    }

    @Override
    public void setUseddisk(Long useddisk) {
        this.useddisk = useddisk;
    }

    @Override
    public Integer getRrequestnum() {
        return this.rrequestnum;
    }

    @Override
    public void setRrequestnum(Integer rrequestnum) {
        this.rrequestnum = rrequestnum;
    }

    @Override
    public Integer getWrequestnum() {
        return this.wrequestnum;
    }

    @Override
    public void setWrequestnum(Integer wrequestnum) {
        this.wrequestnum = wrequestnum;
    }

    @Override
    public Long getReadbytes() {
        return this.readbytes;
    }

    @Override
    public void setReadbytes(Long readbytes) {
        this.readbytes = readbytes;
    }

    @Override
    public Long getWritebytes() {
        return this.writebytes;
    }

    @Override
    public void setWritebytes(Long writebytes) {
        this.writebytes = writebytes;
    }

    @Override
    public Long getTimestamp() {
        return this.timestamp;
    }

    @Override
    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InstanceInfo (");

        sb.append(instanceid);
        sb.append(", ").append(vmimageid);
        sb.append(", ").append(totalcpu);
        sb.append(", ").append(totalmem);
        sb.append(", ").append(totaldisk);
        sb.append(", ").append(usedcpu);
        sb.append(", ").append(usedmem);
        sb.append(", ").append(useddisk);
        sb.append(", ").append(rrequestnum);
        sb.append(", ").append(wrequestnum);
        sb.append(", ").append(readbytes);
        sb.append(", ").append(writebytes);
        sb.append(", ").append(timestamp);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IInstanceInfo from) {
        setInstanceid(from.getInstanceid());
        setVmimageid(from.getVmimageid());
        setTotalcpu(from.getTotalcpu());
        setTotalmem(from.getTotalmem());
        setTotaldisk(from.getTotaldisk());
        setUsedcpu(from.getUsedcpu());
        setUsedmem(from.getUsedmem());
        setUseddisk(from.getUseddisk());
        setRrequestnum(from.getRrequestnum());
        setWrequestnum(from.getWrequestnum());
        setReadbytes(from.getReadbytes());
        setWritebytes(from.getWritebytes());
        setTimestamp(from.getTimestamp());
    }

    @Override
    public <E extends IInstanceInfo> E into(E into) {
        into.from(this);
        return into;
    }
}
