/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.pojos;


import com.pandalu.workloadservice.db.tables.interfaces.IK8sContainerInfo;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class K8sContainerInfo implements IK8sContainerInfo {

    private static final long serialVersionUID = 1637440189;

    private String name;
    private String ownerpod;
    private String mincpu;
    private String minmemory;
    private String maxcpu;
    private String maxmemory;
    private ULong  timestamp;

    public K8sContainerInfo() {}

    public K8sContainerInfo(IK8sContainerInfo value) {
        this.name = value.getName();
        this.ownerpod = value.getOwnerpod();
        this.mincpu = value.getMincpu();
        this.minmemory = value.getMinmemory();
        this.maxcpu = value.getMaxcpu();
        this.maxmemory = value.getMaxmemory();
        this.timestamp = value.getTimestamp();
    }

    public K8sContainerInfo(
        String name,
        String ownerpod,
        String mincpu,
        String minmemory,
        String maxcpu,
        String maxmemory,
        ULong  timestamp
    ) {
        this.name = name;
        this.ownerpod = ownerpod;
        this.mincpu = mincpu;
        this.minmemory = minmemory;
        this.maxcpu = maxcpu;
        this.maxmemory = maxmemory;
        this.timestamp = timestamp;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String getOwnerpod() {
        return this.ownerpod;
    }

    @Override
    public void setOwnerpod(String ownerpod) {
        this.ownerpod = ownerpod;
    }

    @Override
    public String getMincpu() {
        return this.mincpu;
    }

    @Override
    public void setMincpu(String mincpu) {
        this.mincpu = mincpu;
    }

    @Override
    public String getMinmemory() {
        return this.minmemory;
    }

    @Override
    public void setMinmemory(String minmemory) {
        this.minmemory = minmemory;
    }

    @Override
    public String getMaxcpu() {
        return this.maxcpu;
    }

    @Override
    public void setMaxcpu(String maxcpu) {
        this.maxcpu = maxcpu;
    }

    @Override
    public String getMaxmemory() {
        return this.maxmemory;
    }

    @Override
    public void setMaxmemory(String maxmemory) {
        this.maxmemory = maxmemory;
    }

    @Override
    public ULong getTimestamp() {
        return this.timestamp;
    }

    @Override
    public void setTimestamp(ULong timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("K8sContainerInfo (");

        sb.append(name);
        sb.append(", ").append(ownerpod);
        sb.append(", ").append(mincpu);
        sb.append(", ").append(minmemory);
        sb.append(", ").append(maxcpu);
        sb.append(", ").append(maxmemory);
        sb.append(", ").append(timestamp);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IK8sContainerInfo from) {
        setName(from.getName());
        setOwnerpod(from.getOwnerpod());
        setMincpu(from.getMincpu());
        setMinmemory(from.getMinmemory());
        setMaxcpu(from.getMaxcpu());
        setMaxmemory(from.getMaxmemory());
        setTimestamp(from.getTimestamp());
    }

    @Override
    public <E extends IK8sContainerInfo> E into(E into) {
        into.from(this);
        return into;
    }
}
