/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.pojos;


import com.pandalu.workloadservice.db.tables.interfaces.IK8sPodInfo;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class K8sPodInfo implements IK8sPodInfo {

    private static final long serialVersionUID = 126954988;

    private String uid;
    private String name;
    private String ip;
    private String ownernode;
    private String usedcpu;
    private String usedmemory;
    private ULong  timestamp;

    public K8sPodInfo() {}

    public K8sPodInfo(IK8sPodInfo value) {
        this.uid = value.getUid();
        this.name = value.getName();
        this.ip = value.getIp();
        this.ownernode = value.getOwnernode();
        this.usedcpu = value.getUsedcpu();
        this.usedmemory = value.getUsedmemory();
        this.timestamp = value.getTimestamp();
    }

    public K8sPodInfo(
        String uid,
        String name,
        String ip,
        String ownernode,
        String usedcpu,
        String usedmemory,
        ULong  timestamp
    ) {
        this.uid = uid;
        this.name = name;
        this.ip = ip;
        this.ownernode = ownernode;
        this.usedcpu = usedcpu;
        this.usedmemory = usedmemory;
        this.timestamp = timestamp;
    }

    @Override
    public String getUid() {
        return this.uid;
    }

    @Override
    public void setUid(String uid) {
        this.uid = uid;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String getIp() {
        return this.ip;
    }

    @Override
    public void setIp(String ip) {
        this.ip = ip;
    }

    @Override
    public String getOwnernode() {
        return this.ownernode;
    }

    @Override
    public void setOwnernode(String ownernode) {
        this.ownernode = ownernode;
    }

    @Override
    public String getUsedcpu() {
        return this.usedcpu;
    }

    @Override
    public void setUsedcpu(String usedcpu) {
        this.usedcpu = usedcpu;
    }

    @Override
    public String getUsedmemory() {
        return this.usedmemory;
    }

    @Override
    public void setUsedmemory(String usedmemory) {
        this.usedmemory = usedmemory;
    }

    @Override
    public ULong getTimestamp() {
        return this.timestamp;
    }

    @Override
    public void setTimestamp(ULong timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("K8sPodInfo (");

        sb.append(uid);
        sb.append(", ").append(name);
        sb.append(", ").append(ip);
        sb.append(", ").append(ownernode);
        sb.append(", ").append(usedcpu);
        sb.append(", ").append(usedmemory);
        sb.append(", ").append(timestamp);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IK8sPodInfo from) {
        setUid(from.getUid());
        setName(from.getName());
        setIp(from.getIp());
        setOwnernode(from.getOwnernode());
        setUsedcpu(from.getUsedcpu());
        setUsedmemory(from.getUsedmemory());
        setTimestamp(from.getTimestamp());
    }

    @Override
    public <E extends IK8sPodInfo> E into(E into) {
        into.from(this);
        return into;
    }
}
