/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.pojos;


import com.pandalu.workloadservice.db.tables.interfaces.IPmInfo;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PmInfo implements IPmInfo {

    private static final long serialVersionUID = 1462853064;

    private String  uuid;
    private String  pmid;
    private String  pmname;
    private Integer state;
    private Integer city;
    private String  pmip;
    private Long    totalcpu;
    private Long    totalmem;
    private Long    totalband;
    private Long    totaldisk;
    private Long    usedcpu;
    private Long    usedmem;
    private Long    usedband;
    private Long    useddisk;
    private Integer nvms;
    private Long    timestamp;

    public PmInfo() {}

    public PmInfo(IPmInfo value) {
        this.uuid = value.getUuid();
        this.pmid = value.getPmid();
        this.pmname = value.getPmname();
        this.state = value.getState();
        this.city = value.getCity();
        this.pmip = value.getPmip();
        this.totalcpu = value.getTotalcpu();
        this.totalmem = value.getTotalmem();
        this.totalband = value.getTotalband();
        this.totaldisk = value.getTotaldisk();
        this.usedcpu = value.getUsedcpu();
        this.usedmem = value.getUsedmem();
        this.usedband = value.getUsedband();
        this.useddisk = value.getUseddisk();
        this.nvms = value.getNvms();
        this.timestamp = value.getTimestamp();
    }

    public PmInfo(
        String  uuid,
        String  pmid,
        String  pmname,
        Integer state,
        Integer city,
        String  pmip,
        Long    totalcpu,
        Long    totalmem,
        Long    totalband,
        Long    totaldisk,
        Long    usedcpu,
        Long    usedmem,
        Long    usedband,
        Long    useddisk,
        Integer nvms,
        Long    timestamp
    ) {
        this.uuid = uuid;
        this.pmid = pmid;
        this.pmname = pmname;
        this.state = state;
        this.city = city;
        this.pmip = pmip;
        this.totalcpu = totalcpu;
        this.totalmem = totalmem;
        this.totalband = totalband;
        this.totaldisk = totaldisk;
        this.usedcpu = usedcpu;
        this.usedmem = usedmem;
        this.usedband = usedband;
        this.useddisk = useddisk;
        this.nvms = nvms;
        this.timestamp = timestamp;
    }

    @Override
    public String getUuid() {
        return this.uuid;
    }

    @Override
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    @Override
    public String getPmid() {
        return this.pmid;
    }

    @Override
    public void setPmid(String pmid) {
        this.pmid = pmid;
    }

    @Override
    public String getPmname() {
        return this.pmname;
    }

    @Override
    public void setPmname(String pmname) {
        this.pmname = pmname;
    }

    @Override
    public Integer getState() {
        return this.state;
    }

    @Override
    public void setState(Integer state) {
        this.state = state;
    }

    @Override
    public Integer getCity() {
        return this.city;
    }

    @Override
    public void setCity(Integer city) {
        this.city = city;
    }

    @Override
    public String getPmip() {
        return this.pmip;
    }

    @Override
    public void setPmip(String pmip) {
        this.pmip = pmip;
    }

    @Override
    public Long getTotalcpu() {
        return this.totalcpu;
    }

    @Override
    public void setTotalcpu(Long totalcpu) {
        this.totalcpu = totalcpu;
    }

    @Override
    public Long getTotalmem() {
        return this.totalmem;
    }

    @Override
    public void setTotalmem(Long totalmem) {
        this.totalmem = totalmem;
    }

    @Override
    public Long getTotalband() {
        return this.totalband;
    }

    @Override
    public void setTotalband(Long totalband) {
        this.totalband = totalband;
    }

    @Override
    public Long getTotaldisk() {
        return this.totaldisk;
    }

    @Override
    public void setTotaldisk(Long totaldisk) {
        this.totaldisk = totaldisk;
    }

    @Override
    public Long getUsedcpu() {
        return this.usedcpu;
    }

    @Override
    public void setUsedcpu(Long usedcpu) {
        this.usedcpu = usedcpu;
    }

    @Override
    public Long getUsedmem() {
        return this.usedmem;
    }

    @Override
    public void setUsedmem(Long usedmem) {
        this.usedmem = usedmem;
    }

    @Override
    public Long getUsedband() {
        return this.usedband;
    }

    @Override
    public void setUsedband(Long usedband) {
        this.usedband = usedband;
    }

    @Override
    public Long getUseddisk() {
        return this.useddisk;
    }

    @Override
    public void setUseddisk(Long useddisk) {
        this.useddisk = useddisk;
    }

    @Override
    public Integer getNvms() {
        return this.nvms;
    }

    @Override
    public void setNvms(Integer nvms) {
        this.nvms = nvms;
    }

    @Override
    public Long getTimestamp() {
        return this.timestamp;
    }

    @Override
    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PmInfo (");

        sb.append(uuid);
        sb.append(", ").append(pmid);
        sb.append(", ").append(pmname);
        sb.append(", ").append(state);
        sb.append(", ").append(city);
        sb.append(", ").append(pmip);
        sb.append(", ").append(totalcpu);
        sb.append(", ").append(totalmem);
        sb.append(", ").append(totalband);
        sb.append(", ").append(totaldisk);
        sb.append(", ").append(usedcpu);
        sb.append(", ").append(usedmem);
        sb.append(", ").append(usedband);
        sb.append(", ").append(useddisk);
        sb.append(", ").append(nvms);
        sb.append(", ").append(timestamp);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IPmInfo from) {
        setUuid(from.getUuid());
        setPmid(from.getPmid());
        setPmname(from.getPmname());
        setState(from.getState());
        setCity(from.getCity());
        setPmip(from.getPmip());
        setTotalcpu(from.getTotalcpu());
        setTotalmem(from.getTotalmem());
        setTotalband(from.getTotalband());
        setTotaldisk(from.getTotaldisk());
        setUsedcpu(from.getUsedcpu());
        setUsedmem(from.getUsedmem());
        setUsedband(from.getUsedband());
        setUseddisk(from.getUseddisk());
        setNvms(from.getNvms());
        setTimestamp(from.getTimestamp());
    }

    @Override
    public <E extends IPmInfo> E into(E into) {
        into.from(this);
        return into;
    }
}
