/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables.pojos;


import com.pandalu.workloadservice.db.tables.interfaces.IVmInfo;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VmInfo implements IVmInfo {

    private static final long serialVersionUID = -626398296;

    private String  uuid;
    private String  vmid;
    private String  pmid;
    private String  vmimageid;
    private String  vmname;
    private Integer status;
    private Long    totalcpu;
    private Long    totalmem;
    private Long    totaldisk;
    private Long    totalband;
    private Long    usedcpu;
    private Long    usedmem;
    private Long    useddisk;
    private Long    usedband;
    private ULong   timestamp;

    public VmInfo() {}

    public VmInfo(IVmInfo value) {
        this.uuid = value.getUuid();
        this.vmid = value.getVmid();
        this.pmid = value.getPmid();
        this.vmimageid = value.getVmimageid();
        this.vmname = value.getVmname();
        this.status = value.getStatus();
        this.totalcpu = value.getTotalcpu();
        this.totalmem = value.getTotalmem();
        this.totaldisk = value.getTotaldisk();
        this.totalband = value.getTotalband();
        this.usedcpu = value.getUsedcpu();
        this.usedmem = value.getUsedmem();
        this.useddisk = value.getUseddisk();
        this.usedband = value.getUsedband();
        this.timestamp = value.getTimestamp();
    }

    public VmInfo(
        String  uuid,
        String  vmid,
        String  pmid,
        String  vmimageid,
        String  vmname,
        Integer status,
        Long    totalcpu,
        Long    totalmem,
        Long    totaldisk,
        Long    totalband,
        Long    usedcpu,
        Long    usedmem,
        Long    useddisk,
        Long    usedband,
        ULong   timestamp
    ) {
        this.uuid = uuid;
        this.vmid = vmid;
        this.pmid = pmid;
        this.vmimageid = vmimageid;
        this.vmname = vmname;
        this.status = status;
        this.totalcpu = totalcpu;
        this.totalmem = totalmem;
        this.totaldisk = totaldisk;
        this.totalband = totalband;
        this.usedcpu = usedcpu;
        this.usedmem = usedmem;
        this.useddisk = useddisk;
        this.usedband = usedband;
        this.timestamp = timestamp;
    }

    @Override
    public String getUuid() {
        return this.uuid;
    }

    @Override
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    @Override
    public String getVmid() {
        return this.vmid;
    }

    @Override
    public void setVmid(String vmid) {
        this.vmid = vmid;
    }

    @Override
    public String getPmid() {
        return this.pmid;
    }

    @Override
    public void setPmid(String pmid) {
        this.pmid = pmid;
    }

    @Override
    public String getVmimageid() {
        return this.vmimageid;
    }

    @Override
    public void setVmimageid(String vmimageid) {
        this.vmimageid = vmimageid;
    }

    @Override
    public String getVmname() {
        return this.vmname;
    }

    @Override
    public void setVmname(String vmname) {
        this.vmname = vmname;
    }

    @Override
    public Integer getStatus() {
        return this.status;
    }

    @Override
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public Long getTotalcpu() {
        return this.totalcpu;
    }

    @Override
    public void setTotalcpu(Long totalcpu) {
        this.totalcpu = totalcpu;
    }

    @Override
    public Long getTotalmem() {
        return this.totalmem;
    }

    @Override
    public void setTotalmem(Long totalmem) {
        this.totalmem = totalmem;
    }

    @Override
    public Long getTotaldisk() {
        return this.totaldisk;
    }

    @Override
    public void setTotaldisk(Long totaldisk) {
        this.totaldisk = totaldisk;
    }

    @Override
    public Long getTotalband() {
        return this.totalband;
    }

    @Override
    public void setTotalband(Long totalband) {
        this.totalband = totalband;
    }

    @Override
    public Long getUsedcpu() {
        return this.usedcpu;
    }

    @Override
    public void setUsedcpu(Long usedcpu) {
        this.usedcpu = usedcpu;
    }

    @Override
    public Long getUsedmem() {
        return this.usedmem;
    }

    @Override
    public void setUsedmem(Long usedmem) {
        this.usedmem = usedmem;
    }

    @Override
    public Long getUseddisk() {
        return this.useddisk;
    }

    @Override
    public void setUseddisk(Long useddisk) {
        this.useddisk = useddisk;
    }

    @Override
    public Long getUsedband() {
        return this.usedband;
    }

    @Override
    public void setUsedband(Long usedband) {
        this.usedband = usedband;
    }

    @Override
    public ULong getTimestamp() {
        return this.timestamp;
    }

    @Override
    public void setTimestamp(ULong timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VmInfo (");

        sb.append(uuid);
        sb.append(", ").append(vmid);
        sb.append(", ").append(pmid);
        sb.append(", ").append(vmimageid);
        sb.append(", ").append(vmname);
        sb.append(", ").append(status);
        sb.append(", ").append(totalcpu);
        sb.append(", ").append(totalmem);
        sb.append(", ").append(totaldisk);
        sb.append(", ").append(totalband);
        sb.append(", ").append(usedcpu);
        sb.append(", ").append(usedmem);
        sb.append(", ").append(useddisk);
        sb.append(", ").append(usedband);
        sb.append(", ").append(timestamp);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IVmInfo from) {
        setUuid(from.getUuid());
        setVmid(from.getVmid());
        setPmid(from.getPmid());
        setVmimageid(from.getVmimageid());
        setVmname(from.getVmname());
        setStatus(from.getStatus());
        setTotalcpu(from.getTotalcpu());
        setTotalmem(from.getTotalmem());
        setTotaldisk(from.getTotaldisk());
        setTotalband(from.getTotalband());
        setUsedcpu(from.getUsedcpu());
        setUsedmem(from.getUsedmem());
        setUseddisk(from.getUseddisk());
        setUsedband(from.getUsedband());
        setTimestamp(from.getTimestamp());
    }

    @Override
    public <E extends IVmInfo> E into(E into) {
        into.from(this);
        return into;
    }
}
