/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db;


import com.pandalu.workloadservice.db.tables.InstanceInfo;
import com.pandalu.workloadservice.db.tables.K8sContainerInfo;
import com.pandalu.workloadservice.db.tables.K8sNodeInfo;
import com.pandalu.workloadservice.db.tables.K8sPodInfo;
import com.pandalu.workloadservice.db.tables.Map;
import com.pandalu.workloadservice.db.tables.PmInfo;
import com.pandalu.workloadservice.db.tables.VmInfo;
import com.pandalu.workloadservice.db.tables.Vmimages;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompNetFusion extends SchemaImpl {

    private static final long serialVersionUID = 1159385512;

    /**
     * The reference instance of <code>comp_net_fusion</code>
     */
    public static final CompNetFusion COMP_NET_FUSION = new CompNetFusion();

    /**
     * The table <code>comp_net_fusion.instance_info</code>.
     */
    public final InstanceInfo INSTANCE_INFO = com.pandalu.workloadservice.db.tables.InstanceInfo.INSTANCE_INFO;

    /**
     * The table <code>comp_net_fusion.k8s_container_info</code>.
     */
    public final K8sContainerInfo K8S_CONTAINER_INFO = com.pandalu.workloadservice.db.tables.K8sContainerInfo.K8S_CONTAINER_INFO;

    /**
     * The table <code>comp_net_fusion.k8s_node_info</code>.
     */
    public final K8sNodeInfo K8S_NODE_INFO = com.pandalu.workloadservice.db.tables.K8sNodeInfo.K8S_NODE_INFO;

    /**
     * The table <code>comp_net_fusion.k8s_pod_info</code>.
     */
    public final K8sPodInfo K8S_POD_INFO = com.pandalu.workloadservice.db.tables.K8sPodInfo.K8S_POD_INFO;

    /**
     * The table <code>comp_net_fusion.map</code>.
     */
    public final Map MAP = com.pandalu.workloadservice.db.tables.Map.MAP;

    /**
     * The table <code>comp_net_fusion.pm_info</code>.
     */
    public final PmInfo PM_INFO = com.pandalu.workloadservice.db.tables.PmInfo.PM_INFO;

    /**
     * The table <code>comp_net_fusion.vmimages</code>.
     */
    public final Vmimages VMIMAGES = com.pandalu.workloadservice.db.tables.Vmimages.VMIMAGES;

    /**
     * The table <code>comp_net_fusion.vm_info</code>.
     */
    public final VmInfo VM_INFO = com.pandalu.workloadservice.db.tables.VmInfo.VM_INFO;

    /**
     * No further instances allowed
     */
    private CompNetFusion() {
        super("comp_net_fusion", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            InstanceInfo.INSTANCE_INFO,
            K8sContainerInfo.K8S_CONTAINER_INFO,
            K8sNodeInfo.K8S_NODE_INFO,
            K8sPodInfo.K8S_POD_INFO,
            Map.MAP,
            PmInfo.PM_INFO,
            Vmimages.VMIMAGES,
            VmInfo.VM_INFO);
    }
}
