/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db;


import com.pandalu.workloadservice.db.tables.InstanceInfo;
import com.pandalu.workloadservice.db.tables.K8sContainerInfo;
import com.pandalu.workloadservice.db.tables.K8sNodeInfo;
import com.pandalu.workloadservice.db.tables.K8sPodInfo;
import com.pandalu.workloadservice.db.tables.Map;
import com.pandalu.workloadservice.db.tables.PmInfo;
import com.pandalu.workloadservice.db.tables.VmInfo;
import com.pandalu.workloadservice.db.tables.Vmimages;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>comp_net_fusion</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index INSTANCE_INFO_INS_IMG_FK = Indexes0.INSTANCE_INFO_INS_IMG_FK;
    public static final Index INSTANCE_INFO_PRIMARY = Indexes0.INSTANCE_INFO_PRIMARY;
    public static final Index K8S_CONTAINER_INFO_POD_NAME = Indexes0.K8S_CONTAINER_INFO_POD_NAME;
    public static final Index K8S_CONTAINER_INFO_PRIMARY = Indexes0.K8S_CONTAINER_INFO_PRIMARY;
    public static final Index K8S_NODE_INFO_K8S_N_CITY = Indexes0.K8S_NODE_INFO_K8S_N_CITY;
    public static final Index K8S_NODE_INFO_NAME = Indexes0.K8S_NODE_INFO_NAME;
    public static final Index K8S_NODE_INFO_PRIMARY = Indexes0.K8S_NODE_INFO_PRIMARY;
    public static final Index K8S_POD_INFO_NAME = Indexes0.K8S_POD_INFO_NAME;
    public static final Index K8S_POD_INFO_NODE_NAME = Indexes0.K8S_POD_INFO_NODE_NAME;
    public static final Index K8S_POD_INFO_PRIMARY = Indexes0.K8S_POD_INFO_PRIMARY;
    public static final Index MAP_PRIMARY = Indexes0.MAP_PRIMARY;
    public static final Index PM_INFO_CITY_FK = Indexes0.PM_INFO_CITY_FK;
    public static final Index PM_INFO_PMID = Indexes0.PM_INFO_PMID;
    public static final Index PM_INFO_PRIMARY = Indexes0.PM_INFO_PRIMARY;
    public static final Index VMIMAGES_PRIMARY = Indexes0.VMIMAGES_PRIMARY;
    public static final Index VM_INFO_IMG_FK = Indexes0.VM_INFO_IMG_FK;
    public static final Index VM_INFO_PM_FK = Indexes0.VM_INFO_PM_FK;
    public static final Index VM_INFO_PRIMARY = Indexes0.VM_INFO_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index INSTANCE_INFO_INS_IMG_FK = Internal.createIndex("ins_img_fk", InstanceInfo.INSTANCE_INFO, new OrderField[] { InstanceInfo.INSTANCE_INFO.VMIMAGEID }, false);
        public static Index INSTANCE_INFO_PRIMARY = Internal.createIndex("PRIMARY", InstanceInfo.INSTANCE_INFO, new OrderField[] { InstanceInfo.INSTANCE_INFO.INSTANCEID }, true);
        public static Index K8S_CONTAINER_INFO_POD_NAME = Internal.createIndex("pod_name", K8sContainerInfo.K8S_CONTAINER_INFO, new OrderField[] { K8sContainerInfo.K8S_CONTAINER_INFO.OWNERPOD }, false);
        public static Index K8S_CONTAINER_INFO_PRIMARY = Internal.createIndex("PRIMARY", K8sContainerInfo.K8S_CONTAINER_INFO, new OrderField[] { K8sContainerInfo.K8S_CONTAINER_INFO.NAME, K8sContainerInfo.K8S_CONTAINER_INFO.OWNERPOD }, true);
        public static Index K8S_NODE_INFO_K8S_N_CITY = Internal.createIndex("k8s_n_city", K8sNodeInfo.K8S_NODE_INFO, new OrderField[] { K8sNodeInfo.K8S_NODE_INFO.CITY }, false);
        public static Index K8S_NODE_INFO_NAME = Internal.createIndex("name", K8sNodeInfo.K8S_NODE_INFO, new OrderField[] { K8sNodeInfo.K8S_NODE_INFO.NAME }, false);
        public static Index K8S_NODE_INFO_PRIMARY = Internal.createIndex("PRIMARY", K8sNodeInfo.K8S_NODE_INFO, new OrderField[] { K8sNodeInfo.K8S_NODE_INFO.UID, K8sNodeInfo.K8S_NODE_INFO.NAME }, true);
        public static Index K8S_POD_INFO_NAME = Internal.createIndex("name", K8sPodInfo.K8S_POD_INFO, new OrderField[] { K8sPodInfo.K8S_POD_INFO.NAME }, false);
        public static Index K8S_POD_INFO_NODE_NAME = Internal.createIndex("node_name", K8sPodInfo.K8S_POD_INFO, new OrderField[] { K8sPodInfo.K8S_POD_INFO.OWNERNODE }, false);
        public static Index K8S_POD_INFO_PRIMARY = Internal.createIndex("PRIMARY", K8sPodInfo.K8S_POD_INFO, new OrderField[] { K8sPodInfo.K8S_POD_INFO.UID, K8sPodInfo.K8S_POD_INFO.NAME }, true);
        public static Index MAP_PRIMARY = Internal.createIndex("PRIMARY", Map.MAP, new OrderField[] { Map.MAP.ID }, true);
        public static Index PM_INFO_CITY_FK = Internal.createIndex("city_fk", PmInfo.PM_INFO, new OrderField[] { PmInfo.PM_INFO.CITY }, false);
        public static Index PM_INFO_PMID = Internal.createIndex("pmID", PmInfo.PM_INFO, new OrderField[] { PmInfo.PM_INFO.PMID }, false);
        public static Index PM_INFO_PRIMARY = Internal.createIndex("PRIMARY", PmInfo.PM_INFO, new OrderField[] { PmInfo.PM_INFO.UUID, PmInfo.PM_INFO.PMID }, true);
        public static Index VMIMAGES_PRIMARY = Internal.createIndex("PRIMARY", Vmimages.VMIMAGES, new OrderField[] { Vmimages.VMIMAGES.VMIMAGEID }, true);
        public static Index VM_INFO_IMG_FK = Internal.createIndex("img_fk", VmInfo.VM_INFO, new OrderField[] { VmInfo.VM_INFO.VMIMAGEID }, false);
        public static Index VM_INFO_PM_FK = Internal.createIndex("pm_fk", VmInfo.VM_INFO, new OrderField[] { VmInfo.VM_INFO.PMID }, false);
        public static Index VM_INFO_PRIMARY = Internal.createIndex("PRIMARY", VmInfo.VM_INFO, new OrderField[] { VmInfo.VM_INFO.UUID, VmInfo.VM_INFO.VMID, VmInfo.VM_INFO.PMID, VmInfo.VM_INFO.VMIMAGEID }, true);
    }
}
