/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db;


import com.pandalu.workloadservice.db.tables.InstanceInfo;
import com.pandalu.workloadservice.db.tables.K8sContainerInfo;
import com.pandalu.workloadservice.db.tables.K8sNodeInfo;
import com.pandalu.workloadservice.db.tables.K8sPodInfo;
import com.pandalu.workloadservice.db.tables.Map;
import com.pandalu.workloadservice.db.tables.PmInfo;
import com.pandalu.workloadservice.db.tables.VmInfo;
import com.pandalu.workloadservice.db.tables.Vmimages;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in comp_net_fusion
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>comp_net_fusion.instance_info</code>.
     */
    public static final InstanceInfo INSTANCE_INFO = InstanceInfo.INSTANCE_INFO;

    /**
     * The table <code>comp_net_fusion.k8s_container_info</code>.
     */
    public static final K8sContainerInfo K8S_CONTAINER_INFO = K8sContainerInfo.K8S_CONTAINER_INFO;

    /**
     * The table <code>comp_net_fusion.k8s_node_info</code>.
     */
    public static final K8sNodeInfo K8S_NODE_INFO = K8sNodeInfo.K8S_NODE_INFO;

    /**
     * The table <code>comp_net_fusion.k8s_pod_info</code>.
     */
    public static final K8sPodInfo K8S_POD_INFO = K8sPodInfo.K8S_POD_INFO;

    /**
     * The table <code>comp_net_fusion.map</code>.
     */
    public static final Map MAP = Map.MAP;

    /**
     * The table <code>comp_net_fusion.pm_info</code>.
     */
    public static final PmInfo PM_INFO = PmInfo.PM_INFO;

    /**
     * The table <code>comp_net_fusion.vmimages</code>.
     */
    public static final Vmimages VMIMAGES = Vmimages.VMIMAGES;

    /**
     * The table <code>comp_net_fusion.vm_info</code>.
     */
    public static final VmInfo VM_INFO = VmInfo.VM_INFO;
}
