/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables;


import com.pandalu.workloadservice.db.CompNetFusion;
import com.pandalu.workloadservice.db.Indexes;
import com.pandalu.workloadservice.db.Keys;
import com.pandalu.workloadservice.db.tables.records.K8sPodInfoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class K8sPodInfo extends TableImpl<K8sPodInfoRecord> {

    private static final long serialVersionUID = -805884966;

    /**
     * The reference instance of <code>comp_net_fusion.k8s_pod_info</code>
     */
    public static final K8sPodInfo K8S_POD_INFO = new K8sPodInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<K8sPodInfoRecord> getRecordType() {
        return K8sPodInfoRecord.class;
    }

    /**
     * The column <code>comp_net_fusion.k8s_pod_info.uid</code>. 唯一标识符
     */
    public final TableField<K8sPodInfoRecord, String> UID = createField(DSL.name("uid"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "唯一标识符");

    /**
     * The column <code>comp_net_fusion.k8s_pod_info.name</code>. pod名称
     */
    public final TableField<K8sPodInfoRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "pod名称");

    /**
     * The column <code>comp_net_fusion.k8s_pod_info.ip</code>. pod ip
     */
    public final TableField<K8sPodInfoRecord, String> IP = createField(DSL.name("ip"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "pod ip");

    /**
     * The column <code>comp_net_fusion.k8s_pod_info.ownerNode</code>. 所在node
     */
    public final TableField<K8sPodInfoRecord, String> OWNERNODE = createField(DSL.name("ownerNode"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "所在node");

    /**
     * The column <code>comp_net_fusion.k8s_pod_info.usedCpu</code>. 已使用cpu
     */
    public final TableField<K8sPodInfoRecord, String> USEDCPU = createField(DSL.name("usedCpu"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "已使用cpu");

    /**
     * The column <code>comp_net_fusion.k8s_pod_info.usedMemory</code>. 已使用内存
     */
    public final TableField<K8sPodInfoRecord, String> USEDMEMORY = createField(DSL.name("usedMemory"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "已使用内存");

    /**
     * The column <code>comp_net_fusion.k8s_pod_info.timestamp</code>. 时间戳
     */
    public final TableField<K8sPodInfoRecord, ULong> TIMESTAMP = createField(DSL.name("timestamp"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "时间戳");

    /**
     * Create a <code>comp_net_fusion.k8s_pod_info</code> table reference
     */
    public K8sPodInfo() {
        this(DSL.name("k8s_pod_info"), null);
    }

    /**
     * Create an aliased <code>comp_net_fusion.k8s_pod_info</code> table reference
     */
    public K8sPodInfo(String alias) {
        this(DSL.name(alias), K8S_POD_INFO);
    }

    /**
     * Create an aliased <code>comp_net_fusion.k8s_pod_info</code> table reference
     */
    public K8sPodInfo(Name alias) {
        this(alias, K8S_POD_INFO);
    }

    private K8sPodInfo(Name alias, Table<K8sPodInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private K8sPodInfo(Name alias, Table<K8sPodInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> K8sPodInfo(Table<O> child, ForeignKey<O, K8sPodInfoRecord> key) {
        super(child, key, K8S_POD_INFO);
    }

    @Override
    public Schema getSchema() {
        return CompNetFusion.COMP_NET_FUSION;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.K8S_POD_INFO_NAME, Indexes.K8S_POD_INFO_NODE_NAME, Indexes.K8S_POD_INFO_PRIMARY);
    }

    @Override
    public UniqueKey<K8sPodInfoRecord> getPrimaryKey() {
        return Keys.KEY_K8S_POD_INFO_PRIMARY;
    }

    @Override
    public List<UniqueKey<K8sPodInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<K8sPodInfoRecord>>asList(Keys.KEY_K8S_POD_INFO_PRIMARY);
    }

    @Override
    public K8sPodInfo as(String alias) {
        return new K8sPodInfo(DSL.name(alias), this);
    }

    @Override
    public K8sPodInfo as(Name alias) {
        return new K8sPodInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public K8sPodInfo rename(String name) {
        return new K8sPodInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public K8sPodInfo rename(Name name) {
        return new K8sPodInfo(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, String, String, ULong> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
