/*
 * This file is generated by jOOQ.
 */
package com.pandalu.workloadservice.db.tables;


import com.pandalu.workloadservice.db.CompNetFusion;
import com.pandalu.workloadservice.db.Indexes;
import com.pandalu.workloadservice.db.Keys;
import com.pandalu.workloadservice.db.tables.records.MapRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Map extends TableImpl<MapRecord> {

    private static final long serialVersionUID = 1632075751;

    /**
     * The reference instance of <code>comp_net_fusion.map</code>
     */
    public static final Map MAP = new Map();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MapRecord> getRecordType() {
        return MapRecord.class;
    }

    /**
     * The column <code>comp_net_fusion.map.ID</code>. 物理机所在城市城市代码
     */
    public final TableField<MapRecord, Integer> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "物理机所在城市城市代码");

    /**
     * The column <code>comp_net_fusion.map.name</code>. 物理机所在城市名
     */
    public final TableField<MapRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "物理机所在城市名");

    /**
     * Create a <code>comp_net_fusion.map</code> table reference
     */
    public Map() {
        this(DSL.name("map"), null);
    }

    /**
     * Create an aliased <code>comp_net_fusion.map</code> table reference
     */
    public Map(String alias) {
        this(DSL.name(alias), MAP);
    }

    /**
     * Create an aliased <code>comp_net_fusion.map</code> table reference
     */
    public Map(Name alias) {
        this(alias, MAP);
    }

    private Map(Name alias, Table<MapRecord> aliased) {
        this(alias, aliased, null);
    }

    private Map(Name alias, Table<MapRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Map(Table<O> child, ForeignKey<O, MapRecord> key) {
        super(child, key, MAP);
    }

    @Override
    public Schema getSchema() {
        return CompNetFusion.COMP_NET_FUSION;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MAP_PRIMARY);
    }

    @Override
    public UniqueKey<MapRecord> getPrimaryKey() {
        return Keys.KEY_MAP_PRIMARY;
    }

    @Override
    public List<UniqueKey<MapRecord>> getKeys() {
        return Arrays.<UniqueKey<MapRecord>>asList(Keys.KEY_MAP_PRIMARY);
    }

    @Override
    public Map as(String alias) {
        return new Map(DSL.name(alias), this);
    }

    @Override
    public Map as(Name alias) {
        return new Map(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Map rename(String name) {
        return new Map(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Map rename(Name name) {
        return new Map(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
